// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.TradeHistory.Postgres;

namespace Service.TradeHistory.Postgres.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tradehistory")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Service.TradeHistory.Postgres.TradeHistoryEntity", b =>
                {
                    b.Property<string>("TradeId")
                        .HasColumnType("text");

                    b.Property<string>("AccountId")
                        .HasColumnType("text");

                    b.Property<double>("BaseVolume")
                        .HasColumnType("double precision");

                    b.Property<string>("BrokerId")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InstrumentSymbol")
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<double>("OrderVolume")
                        .HasColumnType("double precision");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double>("QuoteVolume")
                        .HasColumnType("double precision");

                    b.Property<long>("SequenceId")
                        .HasColumnType("bigint");

                    b.Property<long>("TradeNo")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("WalletId")
                        .HasColumnType("text");

                    b.HasKey("TradeId");

                    b.HasIndex("SequenceId");

                    b.HasIndex("WalletId");

                    b.HasIndex("WalletId", "InstrumentSymbol");

                    b.HasIndex("WalletId", "SequenceId");

                    b.HasIndex("WalletId", "InstrumentSymbol", "SequenceId");

                    b.ToTable("trade_history");
                });
#pragma warning restore 612, 618
        }
    }
}
